### ISSUE TITLE
failure on: rails generate ad_man:install

### ISSUE THREAD

**Issue by memoht** [kudelabs/ad_man#7]
macbook-pro:playground joe$ rails generate ad_man:install

[WARNING] Could not load generator "generators/ad_man/install_generator". Error: /Users/joe/.rvm/gems/ruby-1.9.2-p320@playground/gems/ad_man-0.0.10/lib/generators/ad_man/install_generator.rb:10: syntax error, unexpected tSTRING_BEG, expecting keyword_do or '{' or '('
      route("mount AdMan::Engine => "/ad_man")
                                             ^
/Users/joe/.rvm/gems/ruby-1.9.2-p320@playground/gems/ad_man-0.0.10/lib/generators/ad_man/install_generator.rb:14: syntax error, unexpected tIDENTIFIER, expecting keyword_end
      rake "ad_man:install:migrations"

**Comment by zhinanhu** [comment]
Dear Joe,
We have fixed the error,  and we are sorry for our mistake. If you have any problem when using ad_man, please feel free to contact us. Thanks!
BR//

------------------ 原始邮件 ------------------
发件人: "guillermo haas-thompson"notifications@github.com;
发送时间: 2012年9月13日(星期四) 中午11:51
收件人: "kudelabs/ad_man"ad_man@noreply.github.com; 

主题: [ad_man] failure on: rails generate ad_man:install (#7)

macbook-pro:playground joe$ rails generate ad_man:install

[WARNING] Could not load generator "generators/ad_man/install_generator". Error: /Users/joe/.rvm/gems/ruby-1.9.2-p320@playground/gems/ad_man-0.0.10/lib/generators/ad_man/install_generator.rb:10: syntax error, unexpected tSTRING_BEG, expecting keyword_do or '{' or '('
       route("mount AdMan::Engine => "/ad_man")
                                              ^
 /Users/joe/.rvm/gems/ruby-1.9.2-p320@playground/gems/ad_man-0.0.10/lib/generators/ad_man/install_generator.rb:14: syntax error, unexpected tIDENTIFIER, expecting keyword_end
       rake "ad_man:install:migrations"

```
           —
           Reply to this email directly or view it on GitHub.
```

**Comment by memoht** [comment]
Excellent. I just updated and was able to install. BTW thank you for creating this gem. I look forward to using it in my project.
